/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proytectoestructura;

/**
 *
 * @author gabri
 */
public class MainMenu extends javax.swing.JFrame {

    int numFac = 0;
    formulario f = new formulario();
    ReporteTiquete r1 = new ReporteTiquete();
    BusAdd b = new BusAdd();
    Estructuras e = f.getE();
    Estructuras e1 = b.getE();
    Parqueo p = new Parqueo();
    ConductorAdd c = new ConductorAdd();
    EstacionAdd ea = new EstacionAdd();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPar = new javax.swing.JMenuItem();
        menuClien = new javax.swing.JMenuItem();
        menuBus = new javax.swing.JMenuItem();
        menuTiq = new javax.swing.JMenuItem();
        menuChof = new javax.swing.JMenuItem();
        menuEsta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo-bus.jpg"))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MicrosoftTeams-image.png"))); // NOI18N
        jMenu1.setText("Agregar");

        jMenuItem1.setText("Nuevo Tiquete");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agregar Chofer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Agregar Bus");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Agregar Estacion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_check_file_32px_1.png"))); // NOI18N
        jMenu2.setText("Mostrar");

        menuPar.setText("Parqueo");
        menuPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuParActionPerformed(evt);
            }
        });
        jMenu2.add(menuPar);

        menuClien.setText("Ver Clientes");
        menuClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienActionPerformed(evt);
            }
        });
        jMenu2.add(menuClien);

        menuBus.setText("Ver Buses");
        menuBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBusActionPerformed(evt);
            }
        });
        jMenu2.add(menuBus);

        menuTiq.setText("Ver Tiquetes");
        menuTiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTiqActionPerformed(evt);
            }
        });
        jMenu2.add(menuTiq);

        menuChof.setText("Ver Choferes");
        menuChof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChofActionPerformed(evt);
            }
        });
        jMenu2.add(menuChof);

        menuEsta.setText("Ver Estaciones");
        menuEsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstaActionPerformed(evt);
            }
        });
        jMenu2.add(menuEsta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                numFac++;
        f.setTitle("Formulario");
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setLbl_Factura(Integer.toString(numFac));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        c.setE(e1);
        c.setTitle("Formulario_Conductor");
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        b.setVisible(true);
        b.setLocationRelativeTo(null);
        b.setTitle("Agregar Bus");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ea.setE(e);
        ea.setTitle("Estaciones");
        ea.setLocationRelativeTo(null);
        ea.setVisible(true);    
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuParActionPerformed
        p.setLocationRelativeTo(null);
        p.setE(e1);
        p.setVisible(true);
    }//GEN-LAST:event_menuParActionPerformed

    private void menuClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienActionPerformed
        r1.setTxt_Reporte(e.mostrarCola());
        r1.setVisible(true);
        r1.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuClienActionPerformed

    private void menuBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBusActionPerformed
        r1.setTxt_Reporte(e1.mostrarLDS());
        r1.setVisible(true);
        r1.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuBusActionPerformed

    private void menuTiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTiqActionPerformed
        System.out.println(e.mostrarLDC());
        r1.setTxt_Reporte(e.mostrarLDC());
        r1.setVisible(true);
        r1.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuTiqActionPerformed

    private void menuChofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChofActionPerformed
        System.out.println(e1.mostrarLS());
        r1.setTxt_Reporte(e1.mostrarLS());
        r1.setVisible(true);
        r1.setLocationRelativeTo(null);  
    }//GEN-LAST:event_menuChofActionPerformed

    private void menuEstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstaActionPerformed
        ea.setE(e);
        r1.setTxt_Reporte(e.mostrarLSC());
        r1.setVisible(true);
        r1.setLocationRelativeTo(null);  
    }//GEN-LAST:event_menuEstaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuBus;
    private javax.swing.JMenuItem menuChof;
    private javax.swing.JMenuItem menuClien;
    private javax.swing.JMenuItem menuEsta;
    private javax.swing.JMenuItem menuPar;
    private javax.swing.JMenuItem menuTiq;
    // End of variables declaration//GEN-END:variables
}
